name: Releases

on: 
  push:
    tags:
    - 'release.*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Generate release file
        run: ./gradlew --quiet "installDist" && "./build/install/android-cli/bin/android-cli" "parse-unreleased-changelog" "CHANGELOG.MD"
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release.tar.gz,foo/*.txt"
          bodyFile: "CHANGELOG_PARSED.md"
          token: ${{ secrets.GITHUB_TOKEN }}