name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./run.sh parse-unreleased-changelog CHANGELOG.md
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "release.tar.gz,foo/*.txt"
        bodyFile: "CHANGELOG_PARSED.md"
        token: ${{ secrets.GITHUB_TOKEN }}